[package]
name = "rangecutter"
description = "Utilities for working with adjacent ranges"

keywords = ["range"]
categories = ["rust-patterns"]

repository = "https://github.com/literallyvoid/rangecutter"
license = "MIT"

version = "0.1.0"
edition = "2021"

[dependencies]
